// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFlOf-NlMvUcoVZ4fFTxh2oSG8h5JfU0',
    appId: '1:408225466148:web:847c2a8dc04c7bb69955b1',
    messagingSenderId: '408225466148',
    projectId: 'swd61amiguel',
    authDomain: 'swd61amiguel.firebaseapp.com',
    databaseURL: 'https://swd61amiguel-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swd61amiguel.firebasestorage.app',
    measurementId: 'G-0YP8PGDDL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvmsYxEYvNyuyD6oCzlltXe0thVxK9iw',
    appId: '1:408225466148:android:b42cbf708f1dfa049955b1',
    messagingSenderId: '408225466148',
    projectId: 'swd61amiguel',
    databaseURL: 'https://swd61amiguel-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swd61amiguel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmlW9RgSxF44Eo7ZQ6q-Wo-mItDLbDmoo',
    appId: '1:408225466148:ios:97853731644193e89955b1',
    messagingSenderId: '408225466148',
    projectId: 'swd61amiguel',
    databaseURL: 'https://swd61amiguel-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swd61amiguel.firebasestorage.app',
    iosBundleId: 'com.example.miguelValentinoShowroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmlW9RgSxF44Eo7ZQ6q-Wo-mItDLbDmoo',
    appId: '1:408225466148:ios:97853731644193e89955b1',
    messagingSenderId: '408225466148',
    projectId: 'swd61amiguel',
    databaseURL: 'https://swd61amiguel-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swd61amiguel.firebasestorage.app',
    iosBundleId: 'com.example.miguelValentinoShowroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLFlOf-NlMvUcoVZ4fFTxh2oSG8h5JfU0',
    appId: '1:408225466148:web:0c49bf078cc18c7c9955b1',
    messagingSenderId: '408225466148',
    projectId: 'swd61amiguel',
    authDomain: 'swd61amiguel.firebaseapp.com',
    databaseURL: 'https://swd61amiguel-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'swd61amiguel.firebasestorage.app',
    measurementId: 'G-ZDRLHSKBSC',
  );

}